### ISSUE TITLE
[question] Camera stream binding

### ISSUE THREAD

**Issue by archenroot** [STEMLab/3DINV#3]
Hello,
great work! I like it a lot :-) 

Now, imagine I would like to realtime camera streams into 3D model, is it easy to integrate such stuff. Can you point me to code and if possible explain in general how to achieve such functionality?

I can of course write streaming server, etc. the question is more about how to map camera view on 3D models. It will require some model texturing changes and angle conversions of video, etc.

Thank you very much.

Ladislav

**Comment by suheeeee** [comment]
Sorry for the late reply.
In this project we use IndoorGML data which including network information for camera(actually, path for person).
If your 3D model format does not store network like IndoorGML, you should limit the movement of the camera by calculating the boundary of the 3D model's geometry and the position of the camera.
But it has to be implemented differently from our project.
I am sorry for not helping you and thank you for your interest in our project.
