### ISSUE TITLE
[QUESTION] : IndoorGML 3D file

### ISSUE THREAD

**Issue by Rajaune** [STEMLab/3DINV#4]
Hello, you really had a great job, thank you for the share.
Please would you tell me how can I create  a 3D indoorGML file for my map. In fact I saw your project ''InFactory' but apparently it is for the creation of 2D indoorGML files.
thank you

**Comment by kijouneli** [comment]
I'd recommend to use InEditor, which will help you to create 3D IndoorGML data from your floor plan. It is more recent one and well documented. InEditor is found at stemlab/ineditor.

**Comment by Rajaune** [comment]
Thank you!
